# Generated by Django 5.0.1 on 2026-01-30 08:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company/Business name', max_length=255)),
                ('partner_type', models.CharField(choices=[('hotel', 'Hotel Partner'), ('flight', 'Flight Partner'), ('both', 'Hotel & Flight Partner')], default='both', help_text='Type of partner', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Partner description', null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/logos/')),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the partner is verified by admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Hotel name', max_length=255)),
                ('city', models.CharField(help_text='City where hotel is located', max_length=100)),
                ('address', models.TextField(help_text='Full address')),
                ('description', models.TextField(blank=True, help_text='Hotel description', null=True)),
                ('star_rating', models.IntegerField(default=3, help_text='Star rating (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='hotels/')),
                ('amenities', models.TextField(blank=True, help_text='Hotel amenities (comma-separated)', null=True)),
                ('check_in_time', models.TimeField(default='14:00:00', help_text='Check-in time')),
                ('check_out_time', models.TimeField(default='12:00:00', help_text='Check-out time')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the hotel is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='partners.partner')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(help_text='Unique flight number', max_length=20, unique=True)),
                ('origin', models.CharField(help_text='Departure city/airport', max_length=100)),
                ('destination', models.CharField(help_text='Arrival city/airport', max_length=100)),
                ('departure_time', models.DateTimeField(help_text='Departure date and time')),
                ('arrival_time', models.DateTimeField(help_text='Arrival date and time')),
                ('price', models.DecimalField(decimal_places=2, help_text='Base price per seat', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('seats_available', models.IntegerField(default=150, help_text='Number of seats available', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_seats', models.IntegerField(default=150, help_text='Total number of seats', validators=[django.core.validators.MinValueValidator(1)])),
                ('aircraft_type', models.CharField(blank=True, help_text='Type of aircraft', max_length=100, null=True)),
                ('airline_logo', models.ImageField(blank=True, null=True, upload_to='airlines/')),
                ('class_type', models.CharField(default='Economy', help_text='Class type (Economy, Business, First Class)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the flight is available for booking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='partners.partner')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Room type name (e.g., Standard, Deluxe, Suite)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Room description', null=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Price per night', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_occupancy', models.IntegerField(default=2, help_text='Maximum number of guests', validators=[django.core.validators.MinValueValidator(1)])),
                ('rooms_available', models.IntegerField(default=10, help_text='Number of rooms available', validators=[django.core.validators.MinValueValidator(0)])),
                ('room_size', models.DecimalField(blank=True, decimal_places=2, help_text='Room size in square meters', max_digits=6, null=True)),
                ('bed_type', models.CharField(blank=True, help_text='Type of bed (e.g., King, Queen, Twin)', max_length=100, null=True)),
                ('amenities', models.TextField(blank=True, help_text='Room amenities (comma-separated)', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the room type is available for booking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='partners.hotel')),
            ],
            options={
                'verbose_name': 'Room Type',
                'verbose_name_plural': 'Room Types',
                'ordering': ['hotel', 'price_per_night'],
            },
        ),
    ]
