# Generated by Django 5.2.10 on 2026-01-31 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_bio_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='postal_code',
        ),
    ]
