# Generated by Django 5.0.1 on 2026-01-30 12:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique booking ID', unique=True)),
                ('booking_type', models.CharField(choices=[('hotel', 'Hotel Booking'), ('flight', 'Flight Booking')], help_text='Type of booking', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', help_text='Booking status', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total booking amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, help_text='Additional notes or special requests', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlightBookingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_passengers', models.IntegerField(default=1, help_text='Number of passengers', validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_seat', models.DecimalField(decimal_places=2, help_text='Price per seat at time of booking', max_digits=10)),
                ('booking', models.OneToOneField(limit_choices_to={'booking_type': 'flight'}, on_delete=django.db.models.deletion.CASCADE, related_name='flight_details', to='bookings.booking')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='partners.flight')),
            ],
            options={
                'verbose_name': 'Flight Booking Detail',
                'verbose_name_plural': 'Flight Booking Details',
            },
        ),
        migrations.CreateModel(
            name='HotelBookingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(help_text='Check-in date')),
                ('check_out_date', models.DateField(help_text='Check-out date')),
                ('number_of_rooms', models.IntegerField(default=1, help_text='Number of rooms booked', validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_guests', models.IntegerField(default=1, help_text='Total number of guests', validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Price per night at time of booking', max_digits=10)),
                ('number_of_nights', models.IntegerField(help_text='Number of nights', validators=[django.core.validators.MinValueValidator(1)])),
                ('booking', models.OneToOneField(limit_choices_to={'booking_type': 'hotel'}, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_details', to='bookings.booking')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='partners.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='partners.roomtype')),
            ],
            options={
                'verbose_name': 'Hotel Booking Detail',
                'verbose_name_plural': 'Hotel Booking Details',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Ms', 'Ms.'), ('Dr', 'Dr.')], default='Mr', max_length=10)),
                ('first_name', models.CharField(help_text='Passenger first name', max_length=100)),
                ('last_name', models.CharField(help_text='Passenger last name', max_length=100)),
                ('date_of_birth', models.DateField(help_text='Passenger date of birth')),
                ('passport_number', models.CharField(blank=True, help_text='Passport number (for international flights)', max_length=50, null=True)),
                ('flight_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='bookings.flightbookingdetail')),
            ],
            options={
                'verbose_name': 'Passenger',
                'verbose_name_plural': 'Passengers',
            },
        ),
    ]
