# Generated by Django 5.2.10 on 2026-02-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbookingdetail',
            name='passenger_dob',
            field=models.DateField(blank=True, help_text='Passenger date of birth', null=True),
        ),
        migrations.AddField(
            model_name='flightbookingdetail',
            name='passenger_first_name',
            field=models.CharField(blank=True, help_text='Passenger first name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flightbookingdetail',
            name='passenger_last_name',
            field=models.CharField(blank=True, help_text='Passenger last name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flightbookingdetail',
            name='passenger_passport',
            field=models.CharField(blank=True, help_text='Passport number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flightbookingdetail',
            name='passenger_title',
            field=models.CharField(choices=[('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Ms', 'Ms.'), ('Dr', 'Dr.')], default='Mr', help_text='Passenger title', max_length=10),
        ),
    ]
