# Generated by Django 5.2.10 on 2026-02-03 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_add_passenger_to_flightbookingdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
